language: go

before_install:
  - go get -v github.com/Masterminds/glide
  - go get -v gopkg.in/alecthomas/gometalinter.v1
install:
  - gometalinter.v1 --install --vendored-linters

matrix:
  fast_finish: true
  include:
    - env: NAME="go test"
      script: go test $(glide novendor)
    - env: NAME="Fast Linting"
      script: gometalinter.v1 --vendor --deadline=9m --fast --disable=gotype
    - env: NAME="Linting"
      script: gometalinter.v1 --vendor --deadline=9m --disable=gotype
