language: go

before_install:
  - go get -v github.com/Masterminds/glide
  - go get -v gopkg.in/alecthomas/gometalinter.v1
install:
  - gometalinter.v1 --install

script:
  - go test $(glide novendor)
  - gometalinter.v1 --vendor --deadline=9m $(glide novendor)
