apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: player
  labels:
    app: player
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: player
    spec:
      containers:
      - name: player
        image: guilhem/patakube
        args: ["player", "--patator"]
        ports:
        - containerPort: 8080
        env:
        - name: NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        imagePullPolicy: Always
      - name: patator
        image: guilhem/patakube
        args: ["player", "patator", "--port=8081"]
        ports:
        - containerPort: 8081
        imagePullPolicy: Always
