apiVersion: v1
kind: Namespace
metadata:
  name: patakube
---
apiVersion: v1
kind: Namespace
metadata:
  name: player1
---
apiVersion: v1
kind: Namespace
metadata:
  name: player2
---
apiVersion: v1
kind: Namespace
metadata:
  name: player3
