apiVersion: v1
kind: Pod
metadata:
  name: player
  labels:
    app: player
spec:
  containers:
    - name: player
      image: patakube/player
      ports:
        - containerPort: 8080
    - name: patator
      image: patakube/patator
      ports:
        - containerPort: 8081
