apiVersion: v1
kind: Pod
metadata:
  name: target
  labels:
    app: target
spec:
  containers:
    - name: patarget
      image: guilhem/patakube
      args: ["target"]
      ports:
        - containerPort: 8080
